### ISSUE TITLE
Unable to paste local image as browser prevents script from opening local file.

### ISSUE THREAD

**Issue by GrantStreetGroup** [JohnMcLear/ep_copy_paste_images#10]
When I installed the plugin and attempted to copy/paste an image from a screen capture tool, I get the following error in the browser console:

```
Not allowed to load local resource: file:///C:/Users/sarnott/AppData/Local/Temp/SNAGHTML12ac5d3.PNG
```

Seems to defeat the benefit of this plugin.

**Comment by JohnMcLear** [comment]
Pretty sure this works.  Prolly a browser issue.  Will be happy to get a PR with a fix in.

**Comment by JohnMcLear** [comment]
defo works.
