### ISSUE TITLE
report of several bugs

### ISSUE THREAD

**Issue by skupfer** [JohnMcLear/ep_copy_paste_images#14]
I have noticed several problems with this plugin... Just to inform

1. Loss of image quality - I noticed a huge loss in image quality, in both print and pad... I googled a bit and it should be possible to store base64 images without quality loss
2. Deleting images not always possible, either it gets duplicated or simply "stays" - selecting the line above, the image and line below seems to fix it most of the time
3. Jump in pad on resize - Fixed if you select a line near the image
4. Print size doesn't equal size shown in pad

**Comment by skupfer** [comment]
5. For whatever reason, even in new pads, transparent images get inserted into them (sometimes up to 10 in the same place, stacking, which would be impossible normally)

**Comment by JohnMcLear** [comment]
1. We store lossless
2. Please provide exact steps to replicate.
3. Please provide exact steps to replicate.
4. I didn't even know you could print these images...  
5. Please provide exact steps to replicate.
6. Please create individual issues for each bug
