### ISSUE TITLE
 Unhandled promise rejection

### ISSUE THREAD

**Issue by zzkt** [JohnMcLear/ep_copy_paste_images#20]
Looks like the `image_upload` and `copy_paste_images` plugins stopped working somewhere between etherpad versions 1.8.3 and 1.8.4.

...described in more detail [here](https://github.com/citizenos/ep_image_upload/issues/14)

**Comment by JohnMcLear** [comment]
Confirmed:

```TypeError: rep.lines.atIndex(...) is undefined``` on paste

I will bisect to figure out what went wrong and why cause this shouldn't be a broken point.

**Comment by JohnMcLear** [comment]
Found it, https://github.com/ether/etherpad-lite/commit/85217b55e0253e3ee090d4a9435adf91d7a86160#diff-2e57978c59833dd5fb8145631991e63eR658

I will see if I can patch in plugin else I will need to extend the plugin framework to force new line.

**Comment by JohnMcLear** [comment]
Fixed upstream, please pull latest develop

**Comment by zzkt** [comment]
thanks. looks good.
