### ISSUE TITLE
errors on paste & resize

### ISSUE THREAD

**Issue by zzkt** [JohnMcLear/ep_copy_paste_images#22]
using the latest (0.0.19) version of the plugin with develop branch (at 7a076d1) of etherpad, I get the following errors on paste or resize (but otherwise appears to work...)

Firefox `TypeError: $(...).context is undefined in /static/js/require-kernel.js?v=2c8f43e3 line 226 > Function at line 114`

Chrome `Uncaught TypeError: Cannot read property 'className' of undefined in /p/test at line 5`

log `[ERROR] console - Failed to load 'ep_copy_paste_images/static/js/index' for 'ep_copy_paste_images/ep_copy_paste_images/client_hooks/aceRegisterBlockElements': ReferenceError: window is not defined`

**Comment by JohnMcLear** [comment]
ack will peep now

**Comment by zzkt** [comment]
looks like I might need to update...

<img width="872" alt="Screenshot 2020-08-24 at 21 39 18" src="https://user-images.githubusercontent.com/41225/91098814-7148c780-e662-11ea-8362-fabeb61d4841.png">

**Comment by zzkt** [comment]
...and looks like it's working as expected again. thanks.

**Comment by JohnMcLear** [comment]
Wow what a beautiful feature....... :1st_place_medal:
