### ISSUE TITLE
Unable to copy paste image in pad

### ISSUE THREAD

**Issue by vivekvt** [JohnMcLear/ep_copy_paste_images#23]
**I tried copy pasting image from web. But after 1 second image disappears. It is not working**

![Screenshot from 2020-08-28 18-51-46](https://user-images.githubusercontent.com/50275510/91565625-25e33180-e960-11ea-8032-51aa2568be72.png)

do I need to make any changes in settings.json ?

Ubuntu 18.04.5 LTS
Chrome Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by JohnMcLear** [comment]
Try test it without other plugins installed.  It is working.

Also try providfe information on bug reports IE browser, OS etc. etc.

**Comment by vivekvt** [comment]
@JohnMcLear 

Image copy paste is working fine if I am on **http://0.0.0.0:9001**
But it doesn't work on localhost **http://localhost:9001/**

I tried on chrome and firefox.

Ubuntu 18.04.5 LTS
Chrome Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by JohnMcLear** [comment]
Works on localhost for me..  You sure this isn't working for you?

**Comment by JohnMcLear** [comment]
Will re-open if you can provide exact steps to replicate.  I'm unable to do so :)
