### ISSUE TITLE
Failed to load 'ep_copy_paste_images/static/js/index' for 'ep_copy_paste_images/ep_copy_paste_images/client_hooks/collectContentPre': Not a function (anonymous) 

### ISSUE THREAD

**Issue by woeterman94** [JohnMcLear/ep_copy_paste_images#24]
I'm sorry for this, but when I open etherpad with the plugin installed I get:

![image](https://user-images.githubusercontent.com/5755057/96747903-28df2900-13c9-11eb-98e3-ce4aa19beaf1.png)
Happens when using google chrome.

**Comment by JohnMcLear** [comment]
Works fine for me.  Try again now please I just pushed.
