### ISSUE TITLE
No ability to upload an image or insert from URL

### ISSUE THREAD

**Issue by JohnMcLear** [JohnMcLear/ep_copy_paste_images#3]
Behaviour for this needs deciding on before I put pen to paper.

**Comment by descoz-hi** [comment]
So, after almost two years, can I assume this is never going to be implemented?

**Comment by JohnMcLear** [comment]
I'm waiting on someone to document behavior...  can you help?

**Comment by descoz-hi** [comment]
I'm not sure about which behavior needs documenting, but I'm not sure I can help. My current needs are essentially a button to insert images in a pad, that's it.
I'm amazed this is the only plugin that does *anything* with images, and it lacks precisely that.
I'm currently trying to implement that myself, but the general lack of documentation is not making things easy...

**Comment by JohnMcLear** [comment]
I'm available as a gun for hire if you want me to help, feel free to email me.

**Comment by JohnMcLear** [comment]
Closing as I prefer the concept of allowing "upload" to be a separate plugin and this plugin is responsible for how to display and manage images within a pad.
